"""Add event table

Revision ID: a8c3b669df7c
Revises: ef85e24a5ace
Create Date: 2024-11-20 09:49:51.000028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8c3b669df7c'
down_revision: Union[str, None] = 'ef85e24a5ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade():
    # ### commands auto generated by Alembic - adjusted for best practices ### 
    op.create_table(
        'events',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, default=sa.text('uuid_generate_v4()')),
        sa.Column('name_of_event', sa.String(), nullable=False),
        sa.Column('institution_id', sa.UUID(as_uuid=True), sa.ForeignKey('institutions.id', ondelete='CASCADE')),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
        sa.Column('image_url', sa.String(length=255), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('is_online', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False),
        sa.Column('cost', sa.NUMERIC(12, 2), nullable=True),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('subaccount_id', sa.String(), nullable=True),
        sa.Column('is_free', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('currency_code', sa.CHAR(3), nullable=False),
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
